{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinylist.backend.serviceAccountName" . }}
  labels:
    {{- include "tinylist.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
